predict whether a patient is likely to be readmitted to hospital based on the previous details of 
the patient.


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/Train-1617360447408-1660719685476.csv", header=0)


In [ ]:
df.head(5)

index  encounter_id  patient_id             race  gender      age weight  \
0  69375     197029140    51521940         Hispanic    Male  [80-90)      ?   
1  57272     163571946    92631357        Caucasian    Male  [60-70)      ?   
2  82347     256497366    30023982        Caucasian  Female  [50-60)      ?   
3  89608     289891212    93606021  AfricanAmerican  Female  [70-80)      ?   
4  24091      81873900    23464296        Caucasian    Male  [70-80)      ?   

   time_in_hospital medical_specialty  num_lab_procedures  ...  X19   X20  \
0                 4  Emergency/Trauma                  39  ...   No    No   
1                 3  Emergency/Trauma                  34  ...   No    No   
2                 6        Nephrology                  50  ...   No  Down   
3                 5                 ?                  63  ...   No  Down   
4                 9        Psychiatry                  17  ...   No    No   

   X21  X22  X23 X24 X25 change diabetesMed  readmitted  
0   No   No   No  No  No     No         Yes           1  
1   No   No   No  No  No     No          No           0  
2   No   No   No  No  No     Ch         Yes           1  
3   No   No   No  No  No     Ch         Yes           1  
4   No   No   No  No  No     No          No           1  

[5 rows x 49 columns]

In [ ]:
df.tail(5)

index  encounter_id  patient_id       race  gender      age weight  \
66582  39934     124202466    23450508  Caucasian  Female  [70-80)      ?   
66583  47366     145667070    29324601  Caucasian    Male  [80-90)      ?   
66584  76555     231061116     2179062  Caucasian  Female  [60-70)      ?   
66585  25392      84911682    20531754          ?  Female  [80-90)      ?   
66586  51312     153167502    81985473  Caucasian  Female  [80-90)      ?   

       time_in_hospital medical_specialty  num_lab_procedures  ...  X19  \
66582                11  InternalMedicine                  40  ...   No   
66583                 4                 ?                  39  ...   No   
66584                 2                 ?                  24  ...   No   
66585                 4  InternalMedicine                  39  ...   No   
66586                 2                 ?                  38  ...   No   

          X20  X21  X22  X23 X24 X25 change diabetesMed  readmitted  
66582  Steady   No   No   No  No  No     No         Yes           0  
66583      No   No   No   No  No  No     No          No           1  
66584      No   No   No   No  No  No     No         Yes           1  
66585      No   No   No   No  No  No     No          No           0  
66586  Steady   No   No   No  No  No     Ch         Yes           1  

[5 rows x 49 columns]

In [ ]:
df.sample(5)

index  encounter_id  patient_id       race  gender      age weight  \
62813  26188      86528382    94080366  Caucasian    Male  [60-70)      ?   
47345  48061     147109944    91629504  Caucasian  Female  [50-60)      ?   
7945   35840     110674662    19171287  Caucasian  Female  [70-80)      ?   
64512   7332      34873296    86698953  Caucasian  Female  [80-90)      ?   
24307  63908     177877236    85363308  Caucasian  Female  [60-70)      ?   

       time_in_hospital        medical_specialty  num_lab_procedures  ...  \
62813                11         InternalMedicine                  66  ...   
47345                 3                        ?                  81  ...   
7945                  3  ObstetricsandGynecology                  28  ...   
64512                10                        ?                  49  ...   
24307                 3                        ?                   3  ...   

       X19     X20  X21  X22  X23 X24 X25 change diabetesMed  readmitted  
62813   No      Up   No   No   No  No  No     Ch         Yes           1  
47345   No  Steady   No   No   No  No  No     Ch         Yes           0  
7945    No  Steady   No   No   No  No  No     Ch         Yes           0  
64512   No      No   No   No   No  No  No     No         Yes           0  
24307   No      No   No   No   No  No  No     Ch         Yes           1  

[5 rows x 49 columns]

In [ ]:
df.describe()

index  encounter_id    patient_id  time_in_hospital  \
count   66587.000000  6.658700e+04  6.658700e+04      66587.000000   
mean    50903.474282  1.653153e+08  5.422970e+07          4.397510   
std     29480.255515  1.030035e+08  3.878819e+07          2.980995   
min         0.000000  1.573800e+04  1.350000e+02          1.000000   
25%     25166.500000  8.440328e+07  2.338646e+07          2.000000   
50%     51129.000000  1.528504e+08  4.526103e+07          4.000000   
75%     76380.000000  2.305049e+08  8.727185e+07          6.000000   
max    101765.000000  4.438672e+08  1.893494e+08         14.000000   

       num_lab_procedures  num_procedures  num_medications  number_outpatient  \
count        66587.000000    66587.000000     66587.000000       66587.000000   
mean            43.115533        1.331521        16.028744           0.365672   
std             19.630417        1.705746         8.125304           1.221861   
min              1.000000        0.000000         1.000000           0.000000   
25%             31.000000        0.000000        10.000000           0.000000   
50%             44.000000        1.000000        15.000000           0.000000   
75%             57.000000        2.000000        20.000000           0.000000   
max            129.000000        6.000000        81.000000          39.000000   

       number_emergency  number_inpatient        diag_5  number_diagnoses  \
count      66587.000000      66587.000000  66587.000000      66587.000000   
mean           0.200460          0.637602     49.703387          7.424948   
std            0.905503          1.255487     28.864879          1.933061   
min            0.000000          0.000000      0.000283          1.000000   
25%            0.000000          0.000000     24.622056          6.000000   
50%            0.000000          0.000000     49.508499          8.000000   
75%            0.000000          1.000000     74.637294          9.000000   
max           63.000000         19.000000     99.995810         16.000000   

         readmitted  
count  66587.000000  
mean       0.462012  
std        0.498559  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        1.000000  
max        1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66587 entries, 0 to 66586
Data columns (total 49 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   index               66587 non-null  int64  
 1   encounter_id        66587 non-null  int64  
 2   patient_id          66587 non-null  int64  
 3   race                66587 non-null  object 
 4   gender              66587 non-null  object 
 5   age                 66587 non-null  object 
 6   weight              66587 non-null  object 
 7   time_in_hospital    66587 non-null  int64  
 8   medical_specialty   66587 non-null  object 
 9   num_lab_procedures  66587 non-null  int64  
 10  num_procedures      66587 non-null  int64  
 11  num_medications     66587 non-null  int64  
 12  number_outpatient   66587 non-null  int64  
 13  number_emergency    66587 non-null  int64  
 14  number_inpatient    66587 non-null  int64  
 15  diag_1              66587 non-null  object 
 16  diag

In [ ]:
df = df.drop(['index', 'encounter_id', 'patient_id', 'race', 'weight', 'medical_specialty'],axis = 1)

In [ ]:
df.nunique()

gender                    3
age                      10
time_in_hospital         14
num_lab_procedures      113
num_procedures            7
num_medications          71
number_outpatient        33
number_emergency         26
number_inpatient         19
diag_1                  652
diag_2                  656
diag_3                  707
diag_4                  707
diag_5                48911
number_diagnoses         16
X1                        4
X2                        4
X3                        4
X4                        4
X5                        4
X6                        3
X7                        4
X8                        1
X9                        4
X10                       4
X11                       2
X12                       4
X13                       4
X14                       4
X15                       3
X16                       2
X17                       2
X18                       1
X19                       1
X20                       4
X21                 

In [ ]:
df.isnull().sum()

gender                0
age                   0
time_in_hospital      0
num_lab_procedures    0
num_procedures        0
num_medications       0
number_outpatient     0
number_emergency      0
number_inpatient      0
diag_1                0
diag_2                0
diag_3                0
diag_4                0
diag_5                0
number_diagnoses      0
X1                    0
X2                    0
X3                    0
X4                    0
X5                    0
X6                    0
X7                    0
X8                    0
X9                    0
X10                   0
X11                   0
X12                   0
X13                   0
X14                   0
X15                   0
X16                   0
X17                   0
X18                   0
X19                   0
X20                   0
X21                   0
X22                   0
X23                   0
X24                   0
X25                   0
change                0
diabetesMed     

In [ ]:
Age = []
for i in df['age']:
  if i == '[80-90)':
    Age.append(85)
  elif i == '[60-70)':
    Age.append(65)
  elif i == '[50-60)':
    Age.append(55)
  elif i == '[70-80)':
    Age.append(75)
  elif i == '[40-50)':
    Age.append(45)
  elif i == '[20-30)':
    Age.append(25)
  elif i == '[30-40)':
    Age.append(35)
  elif i == '[90-100)':
    Age.append(95)
  elif i == '[0-10)':
    Age.append(5)
  else:
    Age.append(15)

In [ ]:
df['age'] = Age
df.age

0        85
1        65
2        55
3        75
4        75
         ..
66582    75
66583    85
66584    65
66585    85
66586    85
Name: age, Length: 66587, dtype: int64

In [ ]:
df['diag_1'] =  pd.to_numeric(df['diag_1'].apply(lambda x: np.nan if x[0].isnumeric() == False else x))
df['diag_2'] =  pd.to_numeric(df['diag_2'].apply(lambda x: np.nan if x[0].isnumeric() == False else x))
df['diag_3'] =  pd.to_numeric(df['diag_3'].apply(lambda x: np.nan if x[0].isnumeric() == False else x))
df['diag_4'] =  pd.to_numeric(df['diag_4'].apply(lambda x: np.nan if x[0].isnumeric() == False else x))

In [ ]:
df['diag_1'].fillna(df['diag_1'].mean(), inplace=True)
df['diag_2'].fillna(df['diag_1'].mean(), inplace=True)
df['diag_3'].fillna(df['diag_1'].mean(), inplace=True)
df['diag_4'].fillna(df['diag_1'].mean(), inplace=True)

In [ ]:
df['X1'].unique()

array(['None', '>200', 'Norm', '>300'], dtype=object)

In [ ]:
df['X2'].unique()

array(['None', 'Norm', '>8', '>7'], dtype=object)

In [ ]:
df['X3'].unique()

array(['No', 'Steady', 'Up', 'Down'], dtype=object)

In [ ]:
df['X4'].unique()

array(['No', 'Steady', 'Up', 'Down'], dtype=object)

In [ ]:
df['X5'].unique()

array(['No', 'Steady', 'Down', 'Up'], dtype=object)

In [ ]:
df['X6'].unique()

array(['No', 'Steady', 'Up'], dtype=object)

In [ ]:
df['X7'].unique()

array(['No', 'Steady', 'Up', 'Down'], dtype=object)

In [ ]:
df['X8'].unique()

array(['No'], dtype=object)

In [ ]:
df['X9'].unique()

array(['No', 'Steady', 'Up', 'Down'], dtype=object)

In [ ]:
df['X10'].unique()

array(['No', 'Down', 'Steady', 'Up'], dtype=object)

In [ ]:
df['X11'].unique()

array(['No', 'Steady'], dtype=object)

In [ ]:
df['X12'].unique()

array(['No', 'Steady', 'Down', 'Up'], dtype=object)

In [ ]:
df['X13'].unique()

array(['Steady', 'No', 'Up', 'Down'], dtype=object)

In [ ]:
df['X14'].unique()

array(['No', 'Steady', 'Up', 'Down'], dtype=object)

In [ ]:
df['X15'].unique()

array(['No', 'Down', 'Steady'], dtype=object)

In [ ]:
df['X16'].unique()

array(['No', 'Steady'], dtype=object)

In [ ]:
df['X17'].unique()

array(['No', 'Steady'], dtype=object)

In [ ]:
df['X18'].unique()

array(['No'], dtype=object)

In [ ]:
df['X19'].unique()

array(['No'], dtype=object)

In [ ]:
df['X20'].unique()

array(['No', 'Down', 'Up', 'Steady'], dtype=object)

In [ ]:
df['X21'].unique()

array(['No', 'Steady', 'Down', 'Up'], dtype=object)

In [ ]:
df['X22'].unique()

array(['No', 'Steady'], dtype=object)

In [ ]:
df['X23'].unique()

array(['No', 'Steady'], dtype=object)

In [ ]:
df['X24'].unique()

array(['No', 'Steady'], dtype=object)

In [ ]:
df['X25'].unique()

array(['No'], dtype=object)

In [ ]:
df = df.drop(['X6', 'X8', 'X11', 'X15', 'X16', 'X17', 'X18', 'X19', 'X22', 'X23', 'X24', 'X25'], axis=1)

In [ ]:
df.columns

Index(['gender', 'age', 'time_in_hospital', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
       'diag_4', 'diag_5', 'number_diagnoses', 'X1', 'X2', 'X3', 'X4', 'X5',
       'X7', 'X9', 'X10', 'X12', 'X13', 'X14', 'X20', 'X21', 'change',
       'diabetesMed', 'readmitted'],
      dtype='object')

In [ ]:
unique_vals = ['None', 'Norm', '>8', '>7', '>200', '>300','No', 'Steady', 'Up', 'Down']

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
unique_vals1 = le.fit_transform(unique_vals)
unique_vals1

array([6, 7, 3, 2, 0, 1, 5, 8, 9, 4])

In [ ]:
df.replace(unique_vals, unique_vals1, inplace = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66587 entries, 0 to 66586
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   gender              66587 non-null  object 
 1   age                 66587 non-null  int64  
 2   time_in_hospital    66587 non-null  int64  
 3   num_lab_procedures  66587 non-null  int64  
 4   num_procedures      66587 non-null  int64  
 5   num_medications     66587 non-null  int64  
 6   number_outpatient   66587 non-null  int64  
 7   number_emergency    66587 non-null  int64  
 8   number_inpatient    66587 non-null  int64  
 9   diag_1              66587 non-null  float64
 10  diag_2              66587 non-null  float64
 11  diag_3              66587 non-null  float64
 12  diag_4              66587 non-null  float64
 13  diag_5              66587 non-null  float64
 14  number_diagnoses    66587 non-null  int64  
 15  X1                  66587 non-null  int64  
 16  X2  

In [ ]:
df['gender'].unique()

array(['Male', 'Female', 'Unknown/Invalid'], dtype=object)

In [ ]:
g1 = ['Male', 'Female', 'Unknown/Invalid']
g2 = le.fit_transform(g1)

print(g2)

[1 0 2]


In [ ]:
df['gender'].replace(g1, g2, inplace = True)
df['gender'].unique()

array([1, 0, 2])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66587 entries, 0 to 66586
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   gender              66587 non-null  int64  
 1   age                 66587 non-null  int64  
 2   time_in_hospital    66587 non-null  int64  
 3   num_lab_procedures  66587 non-null  int64  
 4   num_procedures      66587 non-null  int64  
 5   num_medications     66587 non-null  int64  
 6   number_outpatient   66587 non-null  int64  
 7   number_emergency    66587 non-null  int64  
 8   number_inpatient    66587 non-null  int64  
 9   diag_1              66587 non-null  float64
 10  diag_2              66587 non-null  float64
 11  diag_3              66587 non-null  float64
 12  diag_4              66587 non-null  float64
 13  diag_5              66587 non-null  float64
 14  number_diagnoses    66587 non-null  int64  
 15  X1                  66587 non-null  int64  
 16  X2  

In [ ]:
df['change'].unique()

array([5, 'Ch'], dtype=object)

In [ ]:
ch1 = ['No', 'Ch']
ch2 = le.fit_transform(ch1)

print(ch2)

[1 0]


In [ ]:
df.replace(ch1,ch2,inplace=True)
df['change'].unique()

array([5, 0])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66587 entries, 0 to 66586
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   gender              66587 non-null  int64  
 1   age                 66587 non-null  int64  
 2   time_in_hospital    66587 non-null  int64  
 3   num_lab_procedures  66587 non-null  int64  
 4   num_procedures      66587 non-null  int64  
 5   num_medications     66587 non-null  int64  
 6   number_outpatient   66587 non-null  int64  
 7   number_emergency    66587 non-null  int64  
 8   number_inpatient    66587 non-null  int64  
 9   diag_1              66587 non-null  float64
 10  diag_2              66587 non-null  float64
 11  diag_3              66587 non-null  float64
 12  diag_4              66587 non-null  float64
 13  diag_5              66587 non-null  float64
 14  number_diagnoses    66587 non-null  int64  
 15  X1                  66587 non-null  int64  
 16  X2  

In [ ]:
df['diabetesMed'].unique()

array(['Yes', 5], dtype=object)

In [ ]:
dm = ['Yes', 5]
dm1 = le.fit_transform(dm)

print(dm1)

[1 0]


In [ ]:
df['diabetesMed'].replace(dm, dm1, inplace=True)
df['diabetesMed'].unique()

array([1, 0])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66587 entries, 0 to 66586
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   gender              66587 non-null  int64  
 1   age                 66587 non-null  int64  
 2   time_in_hospital    66587 non-null  int64  
 3   num_lab_procedures  66587 non-null  int64  
 4   num_procedures      66587 non-null  int64  
 5   num_medications     66587 non-null  int64  
 6   number_outpatient   66587 non-null  int64  
 7   number_emergency    66587 non-null  int64  
 8   number_inpatient    66587 non-null  int64  
 9   diag_1              66587 non-null  float64
 10  diag_2              66587 non-null  float64
 11  diag_3              66587 non-null  float64
 12  diag_4              66587 non-null  float64
 13  diag_5              66587 non-null  float64
 14  number_diagnoses    66587 non-null  int64  
 15  X1                  66587 non-null  int64  
 16  X2  

In [ ]:
x = df.drop('readmitted', axis=1)
y = df['readmitted']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=100)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)
clf.score(x_test, y_test)

0.7127696851379086

In [ ]:
prediction = clf.predict(x_test)

In [ ]:
confusion_matrix(y_test, prediction)

array([[7826, 2925],
       [2813, 6413]])

In [ ]:
def evaluate_model(clf):
    print("Train Accuracy :", accuracy_score(y_train, clf.predict(x_train)))
    print("Train Confusion Matrix:")
    print(confusion_matrix(y_train, clf.predict(x_train)))
    print("-"*50)
    print("Test Accuracy :", accuracy_score(y_test, clf.predict(x_test)))
    print("Test Confusion Matrix:")
    print(confusion_matrix(y_test, clf.predict(x_test)))

In [ ]:
clf = DecisionTreeClassifier(max_depth=3)
clf.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=3)

In [ ]:
evaluate_model(clf)

Train Accuracy : 0.6142244153615104
Train Confusion Matrix:
[[18188  6884]
 [11097 10441]]
--------------------------------------------------
Test Accuracy : 0.6198127847024077
Test Confusion Matrix:
[[7860 2891]
 [4704 4522]]


In [ ]:
clf= DecisionTreeClassifier(min_samples_split=20)
clf.fit(x_train, y_train)

DecisionTreeClassifier(min_samples_split=20)

In [ ]:
evaluate_model(clf)

Train Accuracy : 0.8613816777515555
Train Confusion Matrix:
[[22262  2810]
 [ 3651 17887]]
--------------------------------------------------
Test Accuracy : 0.6536516994543725
Test Confusion Matrix:
[[7483 3268]
 [3651 5575]]


In [ ]:
clf = DecisionTreeClassifier(min_samples_leaf=20, random_state=42)
clf.fit(x_train, y_train)

DecisionTreeClassifier(min_samples_leaf=20, random_state=42)

In [ ]:
evaluate_model(clf)

Train Accuracy : 0.7389186869770435
Train Confusion Matrix:
[[19806  5266]
 [ 6903 14635]]
--------------------------------------------------
Test Accuracy : 0.6256695199479402
Test Confusion Matrix:
[[7268 3483]
 [3995 5231]]


In [ ]:
dt_min_leaf_gini = DecisionTreeClassifier(min_samples_leaf=20, random_state=42, criterion="gini")
dt_min_leaf_gini.fit(x_train, y_train)

DecisionTreeClassifier(min_samples_leaf=20, random_state=42)

In [ ]:
evaluate_model(dt_min_leaf_gini)

Train Accuracy : 0.7389186869770435
Train Confusion Matrix:
[[19806  5266]
 [ 6903 14635]]
--------------------------------------------------
Test Accuracy : 0.6256695199479402
Test Confusion Matrix:
[[7268 3483]
 [3995 5231]]


In [ ]:
dt = DecisionTreeClassifier(random_state=42)

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
params = {
    'max_depth': [2, 3, 5, 10, 20],
    'min_samples_leaf': [5, 10, 20, 50, 100],
    'criterion': ["gini", "entropy"]
}

In [ ]:
grid_search = GridSearchCV(estimator=dt, 
                           param_grid=params, 
                           cv=4, n_jobs=-1, verbose=1, scoring = "accuracy")

In [ ]:
grid_search.fit(x_train, y_train)

Fitting 4 folds for each of 50 candidates, totalling 200 fits


GridSearchCV(cv=4, estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 5, 10, 20],
                         'min_samples_leaf': [5, 10, 20, 50, 100]},
             scoring='accuracy', verbose=1)

In [ ]:
grid_search.best_estimator_

DecisionTreeClassifier(max_depth=20, min_samples_leaf=5, random_state=42)

In [ ]:
dt_best = grid_search.best_estimator_

In [ ]:
evaluate_model(dt_best)

Train Accuracy : 0.8063291139240506
Train Confusion Matrix:
[[21359  3713]
 [ 5314 16224]]
--------------------------------------------------
Test Accuracy : 0.6423386894929168
Test Confusion Matrix:
[[7510 3241]
 [3904 5322]]
